### ISSUE TITLE
Bugs and not working because of cvxpy

### ISSUE THREAD

**Issue by tommyvcc** [andruekonst/weighted-random-survival-forest#2]
Dear 
I hope all is well.
Thank you very much for the hard work.
I have been trying to run the package on Google colab and on my laptop with Windows environment, however not working  and getting the following error:
"The latest version of cvxpy doesn't use sum_entries "

I tried to use older version of cvxpy (0.2.9),
But getting another error " module variables. expressions  not found"

I wonder if you can very kindly help me fix this error?

**Comment by andruekonst** [comment]
Thank you!
The cvxpy interface has changed (see [this](https://stackoverflow.com/questions/53943840/cvxpy-import-error-sum-entries-is-not-defined)), so I've updated the code to match the current cvxpy version (1.1.17):  https://github.com/andruekonst/weighted-random-survival-forest/commit/88b833776d1e6fc52d9b9412f97edf5d3df7e660.
